const data = [
  {
    title: 'Category',
    items: ['Instant Games', 'Table Games', 'Video Slots'],
  },
  {
    title: 'Languages',
    search: true,
    items: [
      'English',
      'Ukrainian',
      'Russian',
      'Сhinese (Simple)',
      'Chinese (Traditional)',
      'Turkish',
      'Portuguese',
      'Polish',
      'French',
      'Spanish',
      'German',
      'Italian',
      'Romanian',
      'Bulgarian',
      'Croatian',
      'Japanese',
      'Korean',
      'Indonesian',
      'Vietnamese',
      'Lithuian',
      'Swedish',
      'Finnish',
      'Uzbek',
      'ENS',
    ],
  },
  {
    title: 'RTP',
    items: ['>=97%', '96%', '95%', '94%', '<=93%'],
  },
  {
    title: 'Volatility',
    items: [
      'high high',
      'high med',
      'high low',
      'med high',
      'med med',
      'med low',
      'low high',
      'low med',
      'low low',
    ],
  },
  {
    title: 'Features',
    search: true,
    items: [
      'Expanding Symbols',
      'Sticky Wilds',
      'Expanding Wilds',
      'Random Wilds',
      'Situational Wild symbols',
      'Shifting Wilds',
      'Walking Wilds',
      'Specials Wilds',
      'Nudging Wilds',
      'Connected Symbols',
      'Accumulative Scatter symbols',
      'Replace Random Symbols',
      'Mystery Symbols',
      'Scroll Symbols',
      'Magician symbols',
      'Trigger symbols',
      'Pop symbols',
      'Extra Symbol',
      'Extra Bonus',
      'Free Spins',
      'Extra Free Spins',
      'Free Spins Multiplier',
      'Unlimited Free Spins',
      'Bonus Game',
      'Bonus Symbols',
      'Respin Feature',
      'Multipliers',
      'Games levels',
      'Random Events',
      'Drops and Wins',
      'Group Wins',
      'Random Event Multiplier',
      'Pattern Feature',
      'Wheel of Fortune',
      'Catch Area',
      'Ultra Spin Bonus',
      'Mega stacks feature',
      'Expanding Reels',
      'Double Chance',
      'Money Collect',
      'Reels Syncronisation',
      'Jackpots',
      'Jackpot symbols',
      'Jackpot games',
      'Bonnuss Buy Feature',
      'Scatter Payouts',
      'Bonus Zone',
      'Symbol removal feature',
    ],
  },
  {
    title: 'Tags',
    search: true,
    items: [
      'Jewellery',
      '3D',
      'Adventures',
      'Animals',
      'Arabic',
      'Asia',
      'Auction',
      'Aztec',
      'Baccarat',
      'Bingo',
      'BlackJack',
      'Book',
      'Buying Feature',
      'Cards',
      'Cartoonish',
      'Chests',
      'Circus/Cabaret',
      'CIS',
      'Classic',
      'Coins',
      'Crash games',
      'Cross Channel',
      'Dice',
      'Egypt',
      'Farm',
      'Fire',
      'Fishing',
      'Food',
      'Football',
      'Fruits',
      'Gangsters/Mafia',
      'Girls',
      'Gladiators',
      'Gods',
      'Halloween',
      'Holiday themed',
      'Innovations',
      'Irish themed',
      'Jackpots',
      'Lottery',
      'Magical',
      'Match 3',
      'Mine Sweepers',
      'Money',
      'Mysterious',
      'Other',
      'Pirates',
      'Poker',
      'Roulette',
      'Scratch',
      'Sea',
      'Sevens',
      'Spooky',
      'Sport',
      'Sports/Betting',
      'Summer',
      'Sweets',
      'Tetris',
      'Treasures',
      'Vikings',
      'Wheels',
      'Wild West',
      'Witches',
      'Carnival',
    ],
  },
  {
    title: 'Marker',
    items: [
      'New Game',
      'EVOPLAY’s Сhoice',
      'TOP Asia',
      'TOP Europe',
      'TOP Asia/Europe',
      'Unique Graphics',
    ],
  },
  {
    title: 'Promo tools',
    items: ['Tournament Feature', 'Quests'],
  },
];

export default data;
