import Img1 from 'images/HomePage/LatestReleases/Megagreatestcatchbonus_288x375.jpg';
import Img2 from 'images/HomePage/LatestReleases/funnyhunting_288x375.jpg';
import Img3 from 'images/HomePage/LatestReleases/SoldIt_288x375.jpg';
import Img4 from 'images/HomePage/LatestReleases/wonderfarmbonusbuy_288x375.jpg';
import Img5 from 'images/HomePage/LatestReleases/treasuresofthegods_288x375.jpg';

export const data = [
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    type: 'New Game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1000,
  },
  {
    img: Img2,
    title: 'Funny Hunting',
    category: 'Instant game',
    type: 'TOP Performer',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins'],
    tags: ['Book', 'Aztec'],
    id: 1001,
  },
  {
    img: Img3,
    title: 'Sold it!',
    category: 'Table Games',
    type: 'EVOPLAY’s Сhoice',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: [
      'Free Spins',
      'Free Spins2',
      'Free Spins3',
      'Free Spins4',
      'Free Spins5',
      'Free Spins6',
      'Free Spins7',
      'Free Spins8',
      'Free Spins9',
      'Free Spins10',
      'Free Spins11',
      'Free Spins12',
    ],
    tags: [
      'Book',
      'Aztec',
      'Jewellery',
      'Baccarat',
      'Farm',
      'Book',
      'Aztec',
      'Jewellery',
      'Baccarat',
      'Farm',
      'Book',
      'Aztec',
      'Jewellery',
      'Baccarat',
      'Farm',
      'Book',
      'Aztec',
      'Jewellery',
      'Baccarat',
      'Farm',
    ],
    id: 1002,
  },
  {
    img: Img4,
    title: 'Wonder Farm Bonus Buy',
    category: 'Video slot',
    type: 'Hot Offer',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1003,
  },
  {
    img: Img5,
    title: 'Treasures of the Gods',
    category: 'Instant game',
    type: 'TOP Europe',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1004,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    type: 'TOP Asia/Europe',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1005,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    type: 'TOP Asia',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1006,
  },
  {
    img: Img2,
    title: 'Funny Hunting',
    category: 'Instant game',
    type: 'Unique Graphics',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1007,
  },
  {
    img: Img3,
    title: 'Sold it!',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1008,
  },
  {
    img: Img4,
    title: 'Wonder Farm Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1009,
  },
  {
    img: Img5,
    title: 'Treasures of the Gods',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1010,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1011,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1012,
  },
  {
    img: Img2,
    title: 'Funny Hunting',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1013,
  },
  {
    img: Img3,
    title: 'Sold it!',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1014,
  },
  {
    img: Img4,
    title: 'Wonder Farm Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1015,
  },
  {
    img: Img5,
    title: 'Treasures of the Gods',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1016,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1017,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1018,
  },
  {
    img: Img2,
    title: 'Funny Hunting',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1019,
  },
  {
    img: Img3,
    title: 'Sold it!',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1020,
  },
  {
    img: Img4,
    title: 'Wonder Farm Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1021,
  },
  {
    img: Img5,
    title: 'Treasures of the Gods',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1022,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1023,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1024,
  },
  {
    img: Img2,
    title: 'Funny Hunting',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1025,
  },
  {
    img: Img3,
    title: 'Sold it!',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1026,
  },
  {
    img: Img4,
    title: 'Wonder Farm Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1027,
  },
  {
    img: Img5,
    title: 'Treasures of the Gods',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1028,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1029,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1030,
  },
  {
    img: Img2,
    title: 'Funny Hunting',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1031,
  },
  {
    img: Img3,
    title: 'Sold it!',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1032,
  },
  {
    img: Img4,
    title: 'Wonder Farm Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1033,
  },
  {
    img: Img5,
    title: 'Treasures of the Gods',
    category: 'Instant game',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1034,
  },
  {
    img: Img1,
    title: 'Mega Greatest Catch Bonus Buy',
    category: 'Video slot',
    date: '04.05.2023',
    rtp: 96.01,
    rtpOptions: [92, 94, 96],
    volatility: 'high high',
    paylines: 20,
    minBet: 0.1,
    maxBet: 75,
    maxMultiplier: 77,
    maxWin: 761,
    tournamentFeature: true,
    quests: true,
    progressiveJackpots: false,
    gameFeatures: ['Free Spins', 'Free Spins', 'Free Spins', 'Free Spins'],
    tags: ['Book', 'Aztec', 'Jewellery', 'Baccarat', 'Farm'],
    id: 1035,
  },
];
